//The total surface used by LFont
#define LFONT_MAX_SURFACES 94

//These used by the array of surfaces in LFont
#define LFONT_A 0
#define LFONT_B 1
#define LFONT_C 2
#define LFONT_D 3
#define LFONT_E 4
#define LFONT_F 5
#define LFONT_G 6
#define LFONT_H 7
#define LFONT_I 8
#define LFONT_J 9
#define LFONT_K 10
#define LFONT_L 11
#define LFONT_M 12
#define LFONT_N 13
#define LFONT_O 14
#define LFONT_P 15
#define LFONT_Q 16
#define LFONT_R 17
#define LFONT_S 18
#define LFONT_T 19
#define LFONT_U 20
#define LFONT_V 21
#define LFONT_W 22
#define LFONT_X 23
#define LFONT_Y 24
#define LFONT_Z 25

#define LFONT_a 26
#define LFONT_b 27
#define LFONT_c 28
#define LFONT_d 29
#define LFONT_e 30
#define LFONT_f 31
#define LFONT_g 32
#define LFONT_h 33
#define LFONT_i 34
#define LFONT_j 35
#define LFONT_k 36
#define LFONT_l 37
#define LFONT_m 38
#define LFONT_n 39
#define LFONT_o 40
#define LFONT_p 41
#define LFONT_q 42
#define LFONT_r 43
#define LFONT_s 44
#define LFONT_t 45
#define LFONT_u 46
#define LFONT_v 47
#define LFONT_w 48
#define LFONT_x 49
#define LFONT_y 50
#define LFONT_z 51

#define LFONT_0 52
#define LFONT_1 53
#define LFONT_2 54
#define LFONT_3 55
#define LFONT_4 56
#define LFONT_5 57
#define LFONT_6 58
#define LFONT_7 59
#define LFONT_8 60
#define LFONT_9 61

#define LFONT_EXCLAIM 62
#define LFONT_AT 63
#define LFONT_HASH 64
#define LFONT_DOLLAR 65
#define LFONT_PERCENT 66
#define LFONT_CARET 67
#define LFONT_AMPERSAND 68
#define LFONT_ASTERISK 69
#define LFONT_LEFTPAREN 70
#define LFONT_RIGHTPAREN 71
#define LFONT_MINUS 72
#define LFONT_UNDERSCORE 73
#define LFONT_EQUALS 74
#define LFONT_PLUS 75
#define LFONT_LEFTBRACKET 76
#define LFONT_RIGHTBRACKET 77
#define LFONT_LEFTBRACE 78
#define LFONT_RIGHTBRACE 79
#define LFONT_SEMICOLON 80
#define LFONT_COLON 81
#define LFONT_QUOTE 82
#define LFONT_DBLQUOTE 83
#define LFONT_COMMA 84
#define LFONT_PERIOD 85
#define LFONT_LESS 86
#define LFONT_GREATER 87
#define LFONT_QUESTION 88
#define LFONT_SLASH 89
#define LFONT_LINE 90
#define LFONT_BACKSLASH 91
#define LFONT_BACKQUOTE 92
#define LFONT_TILDE 93

//The flgs ORed into LFont
#define LFONT_TOP 1
#define LFONT_BOTTOM 2
#define LFONT_VCENTER 3
#define LFONT_LEFT 4
#define LFONT_RIGHT 8
#define LFONT_HCENTER 12
#define LFONT_WRAP 16

//some basic colors
#define LWHITE32 0xFFFFFF
#define LBLACK32 0x000000
#define LTRANS32 0x00FFFF
